### ISSUE TITLE
Handling the "No one new around you" case.

### ISSUE THREAD

**Issue by simar7** [ekchang/SwipeRight#1]
Hello,

Thanks for this project. I noticed an issue with the error handling logic in https://github.com/ekchang/SwipeRight/blob/master/app/src/main/java/com/ekc/swiperight/ui/pref/SettingsActivity.java#L82.

When there's no one new around you, the app throws an error which can be seen here: https://goo.gl/photos/an6vmkcGR3jkWJgv6

I'm wondering if the Tinder just does not return anything meaningful when this edge case gets hit or is there another to check for this? Could the user recommendation list count be checked before any interface method on it is invoked?

**Comment by ekchang** [comment]
Good catch! Your screenshot is actually due to [this call in MainPresenter](https://github.com/ekchang/SwipeRight/blob/master/app/src/main/java/com/ekc/swiperight/ui/main/MainPresenter.java#L102). I've seen the error before but didn't realize it was due to "no one new around you."

It does appear the `recommendations()` call is returning null which is why the Observable throws the error. I'll look into it just to be sure and add another error state view.

**Comment by ekchang** [comment]
This has been resolved. The `/recommendations` call returns a single json object `{"message": "recs exhausted"}` which the app now properly catches and displays a meaningful error state.

**Comment by simar7** [comment]
Awesome work!
